### ISSUE TITLE
Implementation leaks memory under certain conditions

### ISSUE THREAD

**Issue by lerdmann** [psmedley/at-funcs#2]
If the buffer required to hold the concatenation of directory name plus the relative filename is larger than what is provided, then the core function "openat_proc_name" will malloc memory.
But that memory will never be freed because it is passed back to the caller. It will therefore leak under that condition.
I think, a better approach in general would be to always allocate dynamically and to always release that memory inside the function calling "openat_proc_name".

**Comment by psmedley** [comment]
Thanks Lars, will try look at this on the weekend...

**Comment by psmedley** [comment]
@lerdmann in gnulib (on which this is loosely based), they have https://github.com/coreutils/gnulib/blob/master/lib/openat.c#L231

Do you think this is sufficient?

**Comment by lerdmann** [comment]
Yes, this is another possible way to do it. Just need to remember to do it this way **every time after** "openat_proc_name" has been called.
